import express from "express";

import auth from "./auth.routes.js";
import leave from "./leave.routes.js";
import permit from "./permit.routes.js";
import overtime from "./overtime.routes.js";
import attendance from "./attendance.routes.js";
import kpi from "./kpi.routes.js";
import tripRoutes from "./trip.routes.js";
import sales from "./sales.routes.js";
import assignment from "./assignment.routes.js";
import announcement from "./announcement.routes.js";
import expenseCategory from "./expenseCategory.routes.js";
import expense from "./expense.routes.js";
import dailyActivity from "./dailyActivity.route.js";
import finance from "./finance.routes.js";
import dashboard from "./dashboard.routes.js";
import termination from "./termination.routes.js";
import organization from "./organization.routes.js";
import resignation from "./resignation.route.js"
import employee from "./employee.routes.js";
import loan from "./loan.routes.js";
import rewardPunishment from "./rewardPunishment.route.js";
import notification from "./notification.routes.js";
import components from "./salaryComponent.routes.js";
import companySetting from "./companySetting.routes.js";
import payroll from "./payroll.routes.js";
import report from "./report.routes.js";
const router = express.Router();

router.use("/", auth);
router.use("/dashboard", dashboard);
router.use("/leave", leave);
router.use("/permit", permit);
router.use("/overtime", overtime);
router.use("/attendance", attendance);
router.use("/employee", employee);
router.use("/organization", organization);
router.use("/kpi", kpi);
router.use("/trip", tripRoutes);
router.use("/daily-activities", dailyActivity);
router.use("/resignation", resignation);
router.use("/terminations", termination);
router.use("/finance", finance);
router.use("/sales", sales);
router.use("/assignments", assignment);
router.use("/announcement", announcement);
router.use("/expense-categories", expenseCategory);
router.use("/expense", expense);
router.use("/loans", loan);
router.use("/reward-punishment", rewardPunishment);
router.use("/components", components);
router.use("/payroll", payroll);
router.use("/company-settings", companySetting);
router.use("/notifications", notification);
router.use("/report", report);

export default router;
