import express from "express";

import authRoutes from "./auth.routes.js";
import leaveRoutes from "./leave.routes.js";
import permitRoutes from "./permit.routes.js";
import overtimeRoutes from "./overtime.routes.js";
import attendanceRoutes from "./attendance.routes.js";
import kpiRoutes from "./kpi.routes.js";
import tripRoutes from "./trip.routes.js";
import salesRoutes from "./sales.routes.js";
import assignmentRoutes from "./assignment.routes.js";
import announcementRoutes from "./announcement.routes.js";
import expenseCategoryRoutes from "./expenseCategory.routes.js";

import expenseRoutes from "./expense.routes.js";
import dailyActivity from "./dailyActivity.route.js";
import finance from "./finance.routes.js";
import dashboardRoutes from "./dashboard.routes.js";
import approvalRoutes from "./approval.routes.js";
import organization from "./organization.routes.js";
import webEmployeeRoutes from "./web/employee.routes.js";
import apiEmployeeRoutes from "./api/employee.routes.js";
import loanRoutes from "./loan.routes.js";
import notificationRoutes from "./notification.routes.js";
import componentPageRoutes from "./componentPage.routes.js";
import salaryComponentRoutes from "./salaryComponent.routes.js";
import payrollRoutes from "./payroll.routes.js";
import reportRoutes from "./report.routes.js";
const router = express.Router();

router.use("/", authRoutes);
router.use("/", dashboardRoutes);
router.use("/", leaveRoutes);
router.use("/permit", permitRoutes);
router.use("/overtime", overtimeRoutes);
router.use("/attendance", attendanceRoutes);
router.use("/employee", webEmployeeRoutes);
router.use("/api/employee", apiEmployeeRoutes);
router.use("/organization", organization);
router.use("/", kpiRoutes);
router.use("/trip", tripRoutes);
router.use("/daily-activities", dailyActivity);
router.use("/approvals", approvalRoutes);
router.use("/finance", finance);
router.use("/sales", salesRoutes);
router.use("/assignments", assignmentRoutes);
router.use("/announcement", announcementRoutes);
router.use("/expense-categories", expenseCategoryRoutes);
router.use("/expense", expenseRoutes);
router.use("/loans", loanRoutes);
router.use("/components", componentPageRoutes);
router.use("/api/components", salaryComponentRoutes);
router.use("/payroll", payrollRoutes);
router.use("/api", notificationRoutes);
router.use("/report", reportRoutes);

export default router;
