import { sessionMiddleware } from "./config/session.js";
import express from "express";
import path from "path";
import { fileURLToPath } from "url";
import { attachPermissions } from "./middlewares/permission.middleware.js";
import ejsMate from "ejs-mate";
import cookieParser from "cookie-parser";
import cors from "cors";
import methodOverride from "method-override";
import session from "express-session";
import MongoStore from "connect-mongo";
import injectUser from "./middlewares/injectUser.js";
import routes from "./routes/index.js";
import "./models/Role.js";
import "./models/User.js";
import "./models/Leave.js";
import "./models/Bidang.js";
import "./models/Unit.js";
import "./models/Position.js";
import "./models/Employee.js";
import "./models/KpiTemplate.js";
import "./models/KpiTemplateDetail.js";
import "./models/UnitKpiMapping.js";
import { globalErrorHandler } from "./middlewares/globalErrorHandler.js";

const app = express();
const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
app.use(cors());
app.use(cookieParser());
app.use(methodOverride("_method"));
app.use(express.json({ limit: "10mb" }));
app.use(express.urlencoded({ extended: true, limit: "10mb" }));
app.use(sessionMiddleware);
app.use(injectUser);
app.use(attachPermissions);
app.use(express.static(path.join(__dirname, "public")));
app.use("/uploads", express.static(path.join(__dirname, "public/uploads")));
app.engine("ejs", ejsMate);
app.set("view engine", "ejs");
app.set("views", path.join(__dirname, "views"));
app.use((req, res, next) => {
  res.locals.user = req.session.user || null;
  next();
});
app.use("/", routes);

app.use(globalErrorHandler);
export default app;
